---
- hosts: rhvm.example.com

  tasks:
    - name: Create shared disk
      ovirt_disks:
        name: "{{ prefix }}_shared_disk"
        format: raw
        shareable: true
        size: 1GiB
        state: detached
        storage_domain: "{{ storage_domain }}"
        wait: true

    - name: Create first VM
      ovirt_vms:
        state: present
        name: "{{ prefix }}_1"
        template: "{{ vm_template }}"
        cluster: "{{ cluster }}"

    - name: Create second VM
      ovirt_vms:
        state: present
        name: "{{ prefix }}_2"
        template: "{{ vm_template }}"
        cluster: "{{ cluster }}"
        wait: true

    - name: Add shared disk
      ovirt_disks:
        name: "{{ prefix }}_shared_disk"
        interface: virtio
        state: attached
        vm_name: "{{ prefix }}_1"

    - name: Add shared disk
      ovirt_disks:
        name: "{{ prefix }}_shared_disk"
        interface: virtio
        state: attached
        vm_name: "{{ prefix }}_2"
